### ISSUE TITLE
[Feature] Traceback handling when connection fails 

### ISSUE THREAD

**Issue by network-shark** [mirceaulinic/salt-sproxy#170]
Hello @mirceaulinic 

**Is your feature request related to a problem? Please describe.**

When running a command against a device which is offline , salt-sproxy returns the traceback (napalm connection ) . 

Why not catch the expection and return only the core information ?

As far as I know salt always returns a dict . 

Why not return a dict, like salt-ssh does  ?

{'r1': {'stdout': '', 'stderr': 'Permission denied, no authentication information', 'retcode': 254}}

This woud feel a bit more salt like and would improve readablity 

Thank You !

**Comment by mirceaulinic** [comment]
The problem is that salt-sproxy is designed to work with whatever Proxy Module. And the implementation and the way the exceptions are raised differs from one implementation to another (there's no standard way in the Proxy Module code). Similarly, even looking at just one particular Proxy Module, e.g., NAPALM, the exception raised depends from one driver to another. Therefore, an uniform message such as `Permission denied, no authentication information` wouldn't be possible as the conditions are far too broad to catch that accurately (every driver, every PM, has a different way to signalize that the username, password, or the hostname are incorrect, or the device is unreachable, etc.).

If the traceback is your main worry, you should probably just correct the authentication details then.
